import Foundation

public struct TweakDraftSelection: Sendable, Equatable {
    public var accepted: [String]
    public var skipped: [String]
    public var truncated: Int

    public init(accepted: [String], skipped: [String] = [], truncated: Int = 0) {
        self.accepted = accepted
        self.skipped = skipped
        self.truncated = truncated
    }

    public var isEmpty: Bool { accepted.isEmpty }
}

public struct TweakDraftWriteResult: Sendable {
    public let directory: URL
    public let files: [URL]
    public let selection: TweakDraftSelection
}

public enum TweakDraftError: LocalizedError {
    case invalidDirectory
    case writeFailed(String)

    public var errorDescription: String? {
        switch self {
        case .invalidDirectory: return L("tweakdraft.error.invalidDirectory")
        case let .writeFailed(path): return L("tweakdraft.error.writeFailed", path)
        }
    }
}

/// 把 Class Dump 识别到的 ObjC 类收成 Logos / Frida 草稿，不捆绑外部 dump 工具。
public enum TweakDraftService {
    public static let hookLimit = 120

    public static let reservedNames: Set<String> = [
        "CDStructures", "NSObject", "NSProxy", "Object", "Protocol"
    ]

    public static func isHookableClassName(_ name: String) -> Bool {
        let trimmed = name.trimmingCharacters(in: .whitespacesAndNewlines)
        guard trimmed.range(of: #"^[A-Za-z_][A-Za-z0-9_]*$"#, options: .regularExpression) != nil else {
            return false
        }
        if reservedNames.contains(trimmed) { return false }
        if trimmed.hasPrefix("$") || trimmed.hasPrefix("_Tt") { return false }
        return true
    }

    public static func selectClassNames(_ names: [String], limit: Int = hookLimit) -> TweakDraftSelection {
        var seen = Set<String>()
        var accepted: [String] = []
        var skipped: [String] = []
        for raw in names {
            let name = raw.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !name.isEmpty else { continue }
            guard isHookableClassName(name) else {
                if seen.insert("skip:" + name).inserted { skipped.append(name) }
                continue
            }
            guard seen.insert(name).inserted else { continue }
            accepted.append(name)
        }
        accepted.sort { $0.localizedStandardCompare($1) == .orderedAscending }
        let overflow = max(0, accepted.count - max(0, limit))
        if overflow > 0 {
            accepted = Array(accepted.prefix(limit))
        }
        return TweakDraftSelection(accepted: accepted, skipped: skipped, truncated: overflow)
    }

    /// Frida 可以按运行时字符串查找，不必是合法 Logos 标识符。
    public static func selectTraceNames(_ names: [String], limit: Int = hookLimit) -> TweakDraftSelection {
        var seen = Set<String>()
        var accepted: [String] = []
        var skipped: [String] = []
        for raw in names {
            let name = raw.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !name.isEmpty else { continue }
            if reservedNames.contains(name) {
                if seen.insert("skip:" + name).inserted { skipped.append(name) }
                continue
            }
            guard seen.insert(name).inserted else { continue }
            accepted.append(name)
        }
        accepted.sort { $0.localizedStandardCompare($1) == .orderedAscending }
        let overflow = max(0, accepted.count - max(0, limit))
        if overflow > 0 {
            accepted = Array(accepted.prefix(limit))
        }
        return TweakDraftSelection(accepted: accepted, skipped: skipped, truncated: overflow)
    }

    public static func tweakSource(classNames: [String], limit: Int = hookLimit) -> String {
        let selection = selectClassNames(classNames, limit: limit)
        var lines = [
            "#import <UIKit/UIKit.h>",
            "",
            "// Generated by Mac小助手 — 仅作 Hook 起点，请按目标进程改 filter 与方法。",
            ""
        ]
        if selection.truncated > 0 {
            lines.append("// 类过多，已截到 \(selection.accepted.count) 个，另有 \(selection.truncated) 个未写入。")
            lines.append("")
        }
        if selection.accepted.isEmpty {
            lines.append("// 未识别到可 hook 的 ObjC 类，请手动添加。")
            lines.append("")
            lines.append("%hook SpringBoard")
            lines.append("")
            lines.append("- (void)applicationDidFinishLaunching:(id)application {")
            lines.append("    %orig;")
            lines.append("}")
            lines.append("")
            lines.append("%end")
            lines.append("")
            return lines.joined(separator: "\n")
        }
        lines.append("// 自动识别到的类 Hook 模板（\(selection.accepted.count) 个）")
        lines.append("")
        for name in selection.accepted {
            lines.append("%hook \(name)")
            lines.append("")
            lines.append("// 添加方法 hook")
            lines.append("// - (void)method { %orig; }")
            lines.append("")
            lines.append("%end")
            lines.append("")
        }
        return lines.joined(separator: "\n")
    }

    public static func fridaTraceScript(classNames: [String], limit: Int = hookLimit) -> String {
        let selection = selectTraceNames(classNames, limit: limit)
        let listed = selection.accepted.map { "        \(jsStringLiteral($0))" }.joined(separator: ",\n")
        return """
        /*
         * trace.js
         * Generated by Mac小助手
         * Usage: frida -U -l trace.js -f com.your.app
         */

        if (ObjC.available) {
            console.log("Frida is ready, ObjC is available.");

            var classesToTrace = [
        \(listed)
            ];

            classesToTrace.forEach(function(className) {
                try {
                    var cls = ObjC.classes[className];
                    if (!cls) {
                        return;
                    }
                    console.log("Adding hooks for class: " + className);

                    var methods = cls.$ownMethods;
                    methods.forEach(function(methodName) {
                        try {
                            Interceptor.attach(cls[methodName].implementation, {
                                onEnter: function(args) {
                                    console.log("\\n[+] " + className + " " + methodName);
                                },
                                onLeave: function(retval) {
                                    console.log("[-] " + className + " " + methodName + " returns: " + retval);
                                }
                            });
                        } catch (err) { }
                    });
                } catch (e) { }
            });
        } else {
            console.log("Objective-C Runtime is not available.");
        }
        """
    }

    public static func jsStringLiteral(_ value: String) -> String {
        var escaped = "\""
        for scalar in value.unicodeScalars {
            switch scalar.value {
            case 0x5C: escaped += "\\\\"
            case 0x22: escaped += "\\\""
            case 0x0A: escaped += "\\n"
            case 0x0D: escaped += "\\r"
            case 0x09: escaped += "\\t"
            case 0..<0x20:
                escaped += String(format: "\\u%04x", scalar.value)
            default:
                escaped.append(Character(scalar))
            }
        }
        escaped += "\""
        return escaped
    }

    public static func write(
        classNames: [String],
        to directory: URL,
        includeTweak: Bool = true,
        includeFrida: Bool = true,
        limit: Int = hookLimit
    ) throws -> TweakDraftWriteResult {
        guard includeTweak || includeFrida else {
            throw TweakDraftError.invalidDirectory
        }
        let selection = selectClassNames(classNames, limit: limit)
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        guard FileSystemHelper.isDirectory(directory) else {
            throw TweakDraftError.invalidDirectory
        }
        var files: [URL] = []
        if includeTweak {
            let file = directory.appendingPathComponent("Tweak.xm")
            try tweakSource(classNames: classNames, limit: limit).write(to: file, atomically: true, encoding: .utf8)
            files.append(file)
        }
        if includeFrida {
            let file = directory.appendingPathComponent("trace.js")
            try fridaTraceScript(classNames: classNames, limit: limit).write(to: file, atomically: true, encoding: .utf8)
            files.append(file)
        }
        return TweakDraftWriteResult(directory: directory, files: files, selection: selection)
    }

    /// 从用户丢进来的文件里找出可供 Class Dump 的 Mach-O；`.deb` 只取 tweak dylib，不执行维护脚本。
    public static func dumpTargets(from url: URL) throws -> [URL] {
        let ext = url.pathExtension.lowercased()
        if ext == "deb" {
            return try TweakInjectService.tweakCandidates(inDebAt: url)
        }
        if ext == "framework" {
            let name = url.deletingPathExtension().lastPathComponent
            let candidate = url.appendingPathComponent(name)
            if FileManager.default.isExecutableFile(atPath: candidate.path)
                || FileManager.default.fileExists(atPath: candidate.path) {
                return [candidate]
            }
        }
        return [url]
    }
}
